name: fix_ease
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.2.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7
  shared_preferences: ^2.2.3
  url_launcher:
  share_plus:
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  # dio: ^5.6.0
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    # nunito
    - family: N600
      fonts:
        - asset: assets/fonts/Nunito-Medium.ttf
    - family: N700
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
    - family: N800
      fonts:
        - asset: assets/fonts/Nunito-Extra.ttf
    - family: N900
      fonts:
        - asset: assets/fonts/Nunito-Extra.ttf
    # kabrio 
    - family: K700
      fonts:
        - asset: assets/fonts/Kabrio-Bold.ttf
    - family: K800
      fonts:
        - asset: assets/fonts/Kabrio-Extra.ttf